import { messages } from "./i18n";
const names: Record<string, string[]> = {
  repdigit: [
    "Repdigit number",
    "重复数字数",
    "全桁が同じ",
    "모든 자릿수가 같음",
    "Gleiche Ziffern",
    "Chiffres identiques",
  ],
  five: [
    "At least five repeated digits",
    "至少五个相同数字",
    "同じ数字が5個以上",
    "같은 숫자 다섯 개 이상",
    "Mindestens fünf gleiche",
    "Au moins cinq chiffres identiques",
  ],
  quad: [
    "Exactly four repeated digits",
    "四个相同数字",
    "同じ数字が4個",
    "같은 숫자 네 개",
    "Vier gleiche Ziffern",
    "Quatre chiffres identiques",
  ],
  triple: [
    "Exactly three repeated digits",
    "三个相同数字",
    "同じ数字が3個",
    "같은 숫자 세 개",
    "Drei gleiche Ziffern",
    "Trois chiffres identiques",
  ],
  pairs: [
    "Multiple digit pairs",
    "多组数位对子",
    "2組以上のペア",
    "두 쌍 이상",
    "Doppelpaar",
    "Double paire",
  ],
  repeat: [
    "Exactly one digit pair",
    "一个重复数字",
    "ひとつのペア",
    "한 쌍의 반복 숫자",
    "Eine doppelte Ziffer",
    "Un chiffre répété",
  ],
  run: [
    "Consecutive repeated digits",
    "连续重复数字",
    "同じ数字の連続",
    "같은 숫자 연속",
    "Gleiche Ziffern in Folge",
    "Suite de chiffres identiques",
  ],
  twoDigits: [
    "Exactly two distinct digits",
    "仅两种数字",
    "2種類の数字だけ",
    "두 종류의 숫자만 사용",
    "Nur zwei Ziffernarten",
    "Deux chiffres distincts",
  ],
  palindrome: [
    "Palindrome number",
    "回文数",
    "回文数",
    "회문수",
    "Palindrom",
    "Palindrome",
  ],
  ascending: [
    "Consecutive ascending digits",
    "连续递增",
    "連続する昇順",
    "연속 오름차순",
    "Aufsteigende Folge",
    "Suite croissante",
  ],
  descending: [
    "Consecutive descending digits",
    "连续递减",
    "連続する降順",
    "연속 내림차순",
    "Absteigende Folge",
    "Suite décroissante",
  ],
  ascRun: [
    "Ascending segment",
    "递增片段",
    "昇順の区間",
    "오름차순 구간",
    "Aufsteigender Abschnitt",
    "Segment croissant",
  ],
  descRun: [
    "Descending segment",
    "递减片段",
    "降順の区間",
    "내림차순 구간",
    "Absteigender Abschnitt",
    "Segment décroissant",
  ],
  abab: [
    "ABAB pattern",
    "ABAB 模式",
    "ABABパターン",
    "ABAB 패턴",
    "ABAB-Muster",
    "Motif ABAB",
  ],
  abcabc: [
    "ABCABC pattern",
    "ABCABC 模式",
    "ABCABCパターン",
    "ABCABC 패턴",
    "ABCABC-Muster",
    "Motif ABCABC",
  ],
  parity: [
    "Alternating parity",
    "奇偶交替",
    "奇数・偶数の交互",
    "홀짝 교대",
    "Wechselnde Parität",
    "Parité alternée",
  ],
  zigzag: [
    "Zigzag digits",
    "锯齿序列",
    "ジグザグの桁",
    "지그재그 숫자",
    "Zickzack-Ziffern",
    "Chiffres en zigzag",
  ],
  harshad: [
    "Harshad number",
    "哈沙德数",
    "ハーシャッド数",
    "하샤드 수",
    "Harshad-Zahl",
    "Nombre de Harshad",
  ],
  happy: [
    "Happy number",
    "快乐数",
    "ハッピー数",
    "행복한 수",
    "Fröhliche Zahl",
    "Nombre heureux",
  ],
  prime: ["Prime number", "质数", "素数", "소수", "Primzahl", "Nombre premier"],
  semiprime: [
    "Semiprime",
    "半质数",
    "半素数",
    "반소수",
    "Semiprimzahl",
    "Nombre semi-premier",
  ],
  square: [
    "Perfect square",
    "完全平方数",
    "平方数",
    "완전제곱수",
    "Quadratzahl",
    "Carré parfait",
  ],
  cube: [
    "Perfect cube",
    "完全立方数",
    "立方数",
    "완전세제곱수",
    "Kubikzahl",
    "Cube parfait",
  ],
  power2: [
    "Power of two",
    "二的幂",
    "2の累乗",
    "2의 거듭제곱",
    "Zweierpotenz",
    "Puissance de deux",
  ],
  fibonacci: [
    "Fibonacci number",
    "斐波那契数",
    "フィボナッチ数",
    "피보나치 수",
    "Fibonacci-Zahl",
    "Nombre de Fibonacci",
  ],
  triangular: [
    "Triangular number",
    "三角形数",
    "三角数",
    "삼각수",
    "Dreieckszahl",
    "Nombre triangulaire",
  ],
  factorial: [
    "Factorial",
    "阶乘数",
    "階乗数",
    "계승수",
    "Fakultät",
    "Factorielle",
  ],
  divisible: [
    "At least 100 positive divisors",
    "至少 100 个正约数",
    "約数が多い",
    "약수가 많은 수",
    "Viele Teiler",
    "Nombre à nombreux diviseurs",
  ],
  binaryPal: [
    "Binary palindrome",
    "二进制回文",
    "2進数の回文",
    "이진 회문",
    "Binärpalindrom",
    "Palindrome binaire",
  ],
  binaryOnes: [
    "Mersenne number (binary repunit)",
    "梅森数（二进制全一）",
    "2進数がすべて1",
    "이진수의 모든 자리가 1",
    "Binär nur Einsen",
    "Répunit binaire",
  ],
  hexRepeat: [
    "Hexadecimal repdigit",
    "十六进制重复数",
    "16進数の同一桁",
    "16진수 반복 숫자",
    "Hexadezimale Wiederholung",
    "Chiffres hexadécimaux identiques",
  ],
};
const descriptions: Record<string, string[]> = {
  repdigit: [
    "At least two digits, all identical.",
    "至少两位，且每位相同。",
    "2桁以上で、すべて同じ数字。",
    "두 자리 이상이며 모든 숫자가 같습니다.",
    "Mindestens zwei Ziffern, alle gleich.",
    "Au moins deux chiffres, tous identiques.",
  ],
  five: [
    "One digit appears five or more times; not a full repdigit.",
    "某数字出现至少五次，但不是全部相同。",
    "同じ数字が5回以上。ただし全桁同一は除外。",
    "한 숫자가 다섯 번 이상 나타나며 전체가 같지는 않습니다.",
    "Eine Ziffer mindestens fünfmal, aber nicht alle gleich.",
    "Un chiffre apparaît au moins cinq fois, sans être le seul.",
  ],
  quad: [
    "The most frequent digit appears exactly four times; not all digits are identical.",
    "出现最多的数字恰好四次，但不是全部相同。",
    "最多の数字がちょうど4回。全桁同一は除外。",
    "가장 흔한 숫자가 네 번 나타나며 전체가 같지는 않습니다.",
    "Die häufigste Ziffer genau viermal, nicht alle gleich.",
    "Le chiffre dominant apparaît quatre fois, sans être le seul.",
  ],
  triple: [
    "The most frequent digit appears exactly three times; not all digits are identical.",
    "出现最多的数字恰好三次，但不是全部相同。",
    "最多の数字がちょうど3回。全桁同一は除外。",
    "가장 흔한 숫자가 세 번 나타나며 전체가 같지는 않습니다.",
    "Die häufigste Ziffer genau dreimal, nicht alle gleich.",
    "Le chiffre dominant apparaît trois fois, sans être le seul.",
  ],
  pairs: [
    "At least two pairs, with no digit appearing more than twice.",
    "至少两个对子，且没有数字出现超过两次。",
    "2組以上のペア。3回以上現れる数字はありません。",
    "최소 두 쌍이며 세 번 이상 나타나는 숫자는 없습니다.",
    "Mindestens zwei Paare, keine Ziffer öfter als zweimal.",
    "Au moins deux paires, aucun chiffre plus de deux fois.",
  ],
  repeat: [
    "Exactly one pair; every other digit appears once. Two-digit repdigits are excluded.",
    "恰好一个对子，其余数字各一次；排除两位全重复数。",
    "1組のペアで、他は1回ずつ。2桁の同一数字は除外。",
    "한 쌍만 반복되고 나머지는 한 번씩 나타납니다. 두 자리 반복수는 제외됩니다.",
    "Genau ein Paar, andere Ziffern einmal. Zweistellige Wiederholungen ausgenommen.",
    "Une seule paire, les autres chiffres uniques. Les nombres à deux chiffres identiques sont exclus.",
  ],
  run: [
    "At least three identical digits next to one another; not a full repdigit.",
    "至少三个相同数字相邻，但不是全部相同。",
    "同じ数字が3個以上連続。全桁同一は除外。",
    "같은 숫자가 세 개 이상 연속하며 전체가 같지는 않습니다.",
    "Mindestens drei gleiche Ziffern nebeneinander, nicht alle gleich.",
    "Au moins trois chiffres identiques consécutifs, sans répétition totale.",
  ],
  twoDigits: [
    "Four or more places use exactly two different digits.",
    "四位或以上，仅使用两种数字。",
    "4桁以上で、ちょうど2種類の数字。",
    "네 자리 이상이며 정확히 두 종류의 숫자를 사용합니다.",
    "Mindestens vier Stellen aus genau zwei Ziffernarten.",
    "Au moins quatre places, exactement deux chiffres distincts.",
  ],
  palindrome: [
    "Two or more digits read the same in either direction.",
    "至少两位，从前往后与从后往前读相同。",
    "2桁以上で、前からも後ろからも同じ。",
    "두 자리 이상이며 앞뒤로 읽어도 같습니다.",
    "Mindestens zweistellig, vorwärts wie rückwärts gleich.",
    "Au moins deux chiffres identiques dans les deux sens de lecture.",
  ],
  ascending: [
    "At least three digits; each rises by exactly one.",
    "至少三位，相邻数字依次增加一。",
    "3桁以上で、各桁が1ずつ増加。",
    "세 자리 이상이며 각 숫자가 1씩 증가합니다.",
    "Mindestens drei Ziffern, jeweils genau eins höher.",
    "Au moins trois chiffres, chacun supérieur de un au précédent.",
  ],
  descending: [
    "At least three digits; each falls by exactly one.",
    "至少三位，相邻数字依次减少一。",
    "3桁以上で、各桁が1ずつ減少。",
    "세 자리 이상이며 각 숫자가 1씩 감소합니다.",
    "Mindestens drei Ziffern, jeweils genau eins niedriger.",
    "Au moins trois chiffres, chacun inférieur de un au précédent.",
  ],
  ascRun: [
    "A segment of at least three digits climbs by one; the full number is not a sequence.",
    "局部至少三位连续增加一，但全数不是递增序列。",
    "3桁以上が1ずつ増加。全体の連続昇順は除外。",
    "세 자리 이상인 구간이 1씩 증가하며 전체 수열은 아닙니다.",
    "Ein Abschnitt steigt mindestens dreimal in Einerschritten; keine vollständige Folge.",
    "Un segment d’au moins trois chiffres augmente de un, sans suite complète.",
  ],
  descRun: [
    "A segment of at least three digits falls by one; the full number is not a sequence.",
    "局部至少三位连续减少一，但全数不是递减序列。",
    "3桁以上が1ずつ減少。全体の連続降順は除外。",
    "세 자리 이상인 구간이 1씩 감소하며 전체 수열은 아닙니다.",
    "Ein Abschnitt von mindestens drei Ziffern fällt in Einerschritten; keine vollständige Folge.",
    "Un segment d’au moins trois chiffres diminue de un, sans suite complète.",
  ],
  abab: [
    "At least four places alternate between two distinct digits.",
    "至少四位，两种不同数字交替出现。",
    "4桁以上で、2種類の数字が交互に並ぶ。",
    "네 자리 이상이며 서로 다른 두 숫자가 번갈아 나타납니다.",
    "Mindestens vier Stellen mit zwei abwechselnden Ziffern.",
    "Au moins quatre places alternant deux chiffres distincts.",
  ],
  abcabc: [
    "A three-digit block repeats twice, using at least two distinct digits.",
    "三位数组重复两遍，且至少使用两种数字。",
    "3桁のブロックを2回繰り返し、2種類以上の数字を使用。",
    "세 자리 묶음이 두 번 반복되며 두 종류 이상의 숫자를 사용합니다.",
    "Ein Dreierblock wiederholt sich zweimal, mit mindestens zwei Ziffernarten.",
    "Un bloc de trois chiffres répété deux fois, avec au moins deux chiffres distincts.",
  ],
  parity: [
    "At least four digits alternate between odd and even.",
    "至少四位，奇数与偶数交替。",
    "4桁以上で、奇数と偶数が交互。",
    "네 자리 이상에서 홀수와 짝수가 번갈아 나타납니다.",
    "Mindestens vier Ziffern, abwechselnd ungerade und gerade.",
    "Au moins quatre chiffres alternant pair et impair.",
  ],
  zigzag: [
    "At least four digits strictly alternate between rising and falling.",
    "至少四位，严格交替上升和下降。",
    "4桁以上で、大小が厳密に交互。",
    "네 자리 이상에서 크고 작음이 엄격하게 교대합니다.",
    "Mindestens vier Ziffern, streng abwechselnd steigend und fallend.",
    "Au moins quatre chiffres alternant strictement hausse et baisse.",
  ],
  harshad: [
    "A positive number divisible by the sum of its digits.",
    "能被其数位和整除的正整数。",
    "各桁の和で割り切れる正の整数。",
    "자릿수 합으로 나누어떨어지는 양의 정수입니다.",
    "Eine positive Zahl, teilbar durch ihre Ziffernsumme.",
    "Un entier positif divisible par la somme de ses chiffres.",
  ],
  happy: [
    "Repeatedly summing squared digits eventually reaches 1.",
    "反复计算各位数字平方和，最终得到 1。",
    "各桁の平方和を繰り返すと1に到達。",
    "각 자릿수의 제곱합을 반복하면 1에 도달합니다.",
    "Wiederholte Summen der Ziffernquadrate ergeben schließlich 1.",
    "La somme répétée des carrés des chiffres finit par atteindre 1.",
  ],
  prime: [
    "A number greater than 1 with exactly two positive divisors.",
    "大于 1 且恰有两个正约数。",
    "1より大きく、正の約数が2つだけ。",
    "1보다 크고 양의 약수가 정확히 두 개입니다.",
    "Größer als 1 und genau zwei positive Teiler.",
    "Supérieur à 1, avec exactement deux diviseurs positifs.",
  ],
  semiprime: [
    "A product of two primes, which may be equal.",
    "两个质数的乘积，两个质数可以相同。",
    "2つの素数の積。同じ素数でも可。",
    "같을 수도 있는 두 소수의 곱입니다.",
    "Produkt zweier Primzahlen, die gleich sein dürfen.",
    "Le produit de deux nombres premiers, éventuellement égaux.",
  ],
  square: [
    "The square of a nonnegative integer, including 0 and 1.",
    "非负整数的平方，包括 0 和 1。",
    "0と1を含む非負整数の平方。",
    "0과 1을 포함하는 음이 아닌 정수의 제곱입니다.",
    "Quadrat einer nichtnegativen ganzen Zahl, einschließlich 0 und 1.",
    "Le carré d’un entier positif ou nul, y compris 0 et 1.",
  ],
  cube: [
    "The cube of a nonnegative integer, including 0 and 1.",
    "非负整数的立方，包括 0 和 1。",
    "0と1を含む非負整数の立方。",
    "0과 1을 포함하는 음이 아닌 정수의 세제곱입니다.",
    "Kubus einer nichtnegativen ganzen Zahl, einschließlich 0 und 1.",
    "Le cube d’un entier positif ou nul, y compris 0 et 1.",
  ],
  power2: [
    "2 raised to a nonnegative integer power, including 1.",
    "2 的非负整数次幂，包括 1。",
    "2の非負整数乗。1を含む。",
    "1을 포함한 2의 음이 아닌 정수 거듭제곱입니다.",
    "2 hoch einer nichtnegativen ganzen Zahl, einschließlich 1.",
    "Deux élevé à une puissance entière positive ou nulle, y compris 1.",
  ],
  fibonacci: [
    "A member of the Fibonacci sequence: 0, 1, 2, 3, 5, 8…",
    "斐波那契序列中的数：0、1、2、3、5、8…",
    "フィボナッチ数列の数：0、1、2、3、5、8…",
    "피보나치 수열의 수: 0, 1, 2, 3, 5, 8…",
    "Eine Fibonacci-Zahl: 0, 1, 2, 3, 5, 8…",
    "Un élément de Fibonacci : 0, 1, 2, 3, 5, 8…",
  ],
  triangular: [
    "A sum of consecutive integers starting at 1, with 0 included.",
    "从 1 开始的连续整数之和，也包括 0。",
    "1からの連続整数の和。0も含む。",
    "1부터 연속된 정수의 합이며 0도 포함합니다.",
    "Summe aufeinanderfolgender Zahlen ab 1; 0 zählt mit.",
    "Une somme d’entiers consécutifs depuis 1, avec 0 inclus.",
  ],
  factorial: [
    "A product 1 × 2 × … × k, including 1.",
    "1 × 2 × … × k 的乘积，包括 1。",
    "1 × 2 × … × kの積。1を含む。",
    "1을 포함한 1 × 2 × … × k의 곱입니다.",
    "Ein Produkt 1 × 2 × … × k, einschließlich 1.",
    "Un produit 1 × 2 × … × k, y compris 1.",
  ],
  divisible: [
    "At least 100 distinct positive divisors.",
    "至少有 100 个不同的正约数。",
    "異なる正の約数が100個以上。",
    "서로 다른 양의 약수가 100개 이상입니다.",
    "Mindestens 100 verschiedene positive Teiler.",
    "Au moins 100 diviseurs positifs distincts.",
  ],
  binaryPal: [
    "At least two binary digits read the same in reverse.",
    "至少两位的二进制表示正反相同。",
    "2桁以上の2進数が回文。",
    "두 자리 이상의 이진수가 앞뒤로 같습니다.",
    "Mindestens zwei Binärziffern, rückwärts identisch.",
    "Au moins deux chiffres binaires identiques dans les deux sens.",
  ],
  binaryOnes: [
    "The binary representation has at least two digits, all 1.",
    "二进制至少两位，且全为 1。",
    "2進数が2桁以上で、すべて1。",
    "이진수가 두 자리 이상이며 모두 1입니다.",
    "Mindestens zwei Binärziffern, alle 1.",
    "Au moins deux chiffres binaires, tous égaux à 1.",
  ],
  hexRepeat: [
    "At least two identical digits in hexadecimal notation.",
    "十六进制表示至少两位，且全部相同。",
    "16進数が2桁以上で、全桁が同じ。",
    "16진수가 두 자리 이상이며 모두 같습니다.",
    "Mindestens zwei gleiche Ziffern in Hexadezimaldarstellung.",
    "Au moins deux chiffres hexadécimaux, tous identiques.",
  ],
};
for (const [key, value] of Object.entries(names)) messages["p_" + key] = value;
for (const [key, value] of Object.entries(descriptions))
  messages["d_" + key] = value;
